// ignore_for_file: avoid_print
//
// One-off harness that generates test vectors for
// `TotpWords.deriveLivenessAction`, to be baked as constants in
// `test/crypto/totp_words_liveness_test.dart`.
//
// Matches the derivation spec in `.devloop/plan.md` Task 1.2:
//   HKDF-SHA-256, info = "signet/v2/liveness-action-from-<role>",
//   nonce = 8-byte big-endian window counter, output = 1 byte.
//   action_index = byte & 7 (== byte % 8).
//
// Run: `dart run tool/generate_liveness_vectors.dart`
//
// Not run in CI; artifacts are the baked-in constants.

import 'dart:convert';
import 'dart:typed_data';

import 'package:cryptography/cryptography.dart';

const _actions = <String>[
  'lookUp',
  'lookDown',
  'lookLeft',
  'lookRight',
  'touchNose',
  'touchForehead',
  'touchLeftEar',
  'touchRightEar',
];

Uint8List _counterBe(int counter) {
  final b = Uint8List(8);
  var v = counter;
  for (var i = 7; i >= 0; i--) {
    b[i] = v & 0xFF;
    v >>= 8;
  }
  return b;
}

Future<int> deriveByte({
  required List<int> secret,
  required int counter,
  required String role,
}) async {
  final hkdf = Hkdf(hmac: Hmac.sha256(), outputLength: 1);
  final derived = await hkdf.deriveKey(
    secretKey: SecretKey(secret),
    nonce: _counterBe(counter),
    info: 'signet/v2/liveness-action-from-$role'.codeUnits,
  );
  final bytes = await derived.extractBytes();
  return bytes[0];
}

Future<void> main() async {
  final secret = utf8.encode('12345678901234567890123456789012');
  const cases = <(int, String)>[
    (0, 'a'),
    (0, 'b'),
    (1, 'a'),
    (1, 'b'),
    (37037037, 'a'), // window for unix=1111111111, step=30
    (37037037, 'b'),
    (60000000, 'a'),
    (60000000, 'b'),
    (37037036, 'a'), // ±1 neighbours for tolerance tests
    (37037038, 'a'),
  ];
  print('// Generated by tool/generate_liveness_vectors.dart');
  print('// Secret: utf8("12345678901234567890123456789012")');
  print('//');
  print('// (counter, role, byteHex, actionIndex, actionName)');
  for (final (counter, role) in cases) {
    final byte = await deriveByte(
      secret: secret,
      counter: counter,
      role: role,
    );
    final idx = byte & 7;
    print(
      '// counter=$counter role=$role  byte=0x${byte.toRadixString(16).padLeft(2, '0')}  '
      'actionIndex=$idx  action=${_actions[idx]}',
    );
  }
}
