import 'dart:convert';

import 'package:flutter_test/flutter_test.dart';
import 'package:signet/core/crypto/pair_role.dart';
import 'package:signet/core/crypto/totp_words.dart';

/// TDD vectors for `TotpWords.deriveLivenessAction`.
///
/// Spec: `.devloop/plan.md` Phase 1 (secret-derived liveness).
///   HKDF-SHA-256(
///     secret   = pair shared secret,
///     info     = "signet/v2/liveness-action-from-{role}",
///     nonce    = u64 big-endian window counter,
///     outLen   = 1 byte,
///   ) → byte
///   actionIndex = byte & 7   (equivalently byte % 8)
///   action      = LivenessAction.values[actionIndex]
///
/// Fixture vectors were generated by `tool/generate_liveness_vectors.dart`;
/// re-run that harness if the derivation inputs ever change.
void main() {
  final secret = utf8.encode('12345678901234567890123456789012');

  group('TotpWords.deriveLivenessAction — fixture vectors', () {
    // (counter, role) → expected action.
    // Secret: utf8("12345678901234567890123456789012").
    // Source of truth: tool/generate_liveness_vectors.dart.
    const vectors = <(int, PairRole, LivenessAction)>[
      (0, PairRole.a, LivenessAction.lookLeft),
      (0, PairRole.b, LivenessAction.touchLeftEar),
      (1, PairRole.a, LivenessAction.lookUp),
      (1, PairRole.b, LivenessAction.touchForehead),
      (37037037, PairRole.a, LivenessAction.lookUp), // unix=1111111111
      (37037037, PairRole.b, LivenessAction.touchRightEar),
      (60000000, PairRole.a, LivenessAction.touchForehead),
      (60000000, PairRole.b, LivenessAction.lookLeft),
      (37037036, PairRole.a, LivenessAction.touchForehead), // unix=1111111081
      (37037038, PairRole.a, LivenessAction.touchRightEar), // unix=1111111141
    ];

    for (final (counter, role, expected) in vectors) {
      test('counter=$counter role=${role.wireName} → ${expected.name}',
          () async {
        final action = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: counter * TotpWords.defaultTimeStepSeconds,
          senderRole: role,
        );
        expect(action, equals(expected));
      });
    }
  });

  group('TotpWords.deriveLivenessAction — properties', () {
    const t = 1111111111;

    test('is deterministic for the same inputs', () async {
      final a = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: t,
        senderRole: PairRole.a,
      );
      final b = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: t,
        senderRole: PairRole.a,
      );
      expect(a, equals(b));
    });

    test('is constant across seconds within the same 30-second window',
        () async {
      final a = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: 60,
        senderRole: PairRole.a,
      );
      final b = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: 89,
        senderRole: PairRole.a,
      );
      expect(a, equals(b));
    });

    test('rolls over at the next 30-second window', () async {
      final windowA = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: 60, // window counter = 2
        senderRole: PairRole.a,
      );
      final windowB = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: 90, // window counter = 3
        senderRole: PairRole.a,
      );
      // Two adjacent windows *could* happen to collide (1/8 chance). Our
      // fixture at unix=60 (counter=2) vs unix=90 (counter=3) does not —
      // verified via the generator harness. If the corpus or derivation
      // changes in a way that makes them collide, pick a different pair.
      expect(windowA, isNot(equals(windowB)));
    });

    test('always returns a value from the curated corpus', () async {
      for (var w = 0; w < 200; w++) {
        final action = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: w * 30,
          senderRole: PairRole.a,
        );
        expect(LivenessAction.values, contains(action));
      }
    });

    test('rejects empty secret', () async {
      expect(
        () => TotpWords.deriveLivenessAction(
          secret: const <int>[],
          unixTimeSeconds: 0,
          senderRole: PairRole.a,
        ),
        throwsArgumentError,
      );
    });

    test('rejects non-positive timeStepSeconds', () async {
      expect(
        () => TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: 0,
          senderRole: PairRole.a,
          timeStepSeconds: 0,
        ),
        throwsArgumentError,
      );
    });
  });

  group('TotpWords.deriveLivenessAction — role asymmetry', () {
    // Same defense as TotpWords.generate: an attacker reflecting the
    // verifier's displayed action back at her should fail, because
    // `signet/v2/liveness-action-from-a` and `...from-b` are different
    // HKDF info strings. See .devloop/plan.md Task 1.2.

    test('role a and role b derive different actions for most windows',
        () async {
      // The actions space is 8 elements, so for any given window there's a
      // 1/8 chance of collision. Sampling 100 windows, at least ~80 should
      // differ (expected ~87); assert a loose lower bound so the test is
      // stable across normal derivation outputs.
      var differed = 0;
      for (var w = 0; w < 100; w++) {
        final a = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: w * 30,
          senderRole: PairRole.a,
        );
        final b = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: w * 30,
          senderRole: PairRole.b,
        );
        if (a != b) differed++;
      }
      expect(differed, greaterThan(70));
    });

    test(
      'at unix=1111111111, role a derives lookUp and role b derives '
      'touchRightEar — fixed vector, role-asymmetry cross-check',
      () async {
        final a = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: 1111111111,
          senderRole: PairRole.a,
        );
        final b = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: 1111111111,
          senderRole: PairRole.b,
        );
        expect(a, LivenessAction.lookUp);
        expect(b, LivenessAction.touchRightEar);
        expect(a, isNot(b));
      },
    );
  });

  group('TotpWords.verifyLivenessAction — ±1 window tolerance', () {
    const t = 1111111111;

    test('accepts the exact current window', () async {
      final expected = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: t,
        senderRole: PairRole.a,
      );
      expect(
        await TotpWords.verifyLivenessAction(
          secret: secret,
          candidate: expected,
          unixTimeSeconds: t,
          senderRole: PairRole.a,
        ),
        isTrue,
      );
    });

    test('accepts one window in the past (tolerance ±1)', () async {
      final prev = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: t - 30,
        senderRole: PairRole.a,
      );
      expect(
        await TotpWords.verifyLivenessAction(
          secret: secret,
          candidate: prev,
          unixTimeSeconds: t,
          senderRole: PairRole.a,
        ),
        isTrue,
      );
    });

    test('accepts one window in the future (tolerance ±1)', () async {
      final next = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: t + 30,
        senderRole: PairRole.a,
      );
      expect(
        await TotpWords.verifyLivenessAction(
          secret: secret,
          candidate: next,
          unixTimeSeconds: t,
          senderRole: PairRole.a,
        ),
        isTrue,
      );
    });

    test('accepts windowTolerance=0 only at the exact window', () async {
      final prev = await TotpWords.deriveLivenessAction(
        secret: secret,
        unixTimeSeconds: t - 30,
        senderRole: PairRole.a,
      );
      // With tolerance=0, prev-window action no longer qualifies — UNLESS
      // prev and current happen to collide (1/8 per derivation). Pick a
      // fixture where they DO differ: counter=37037036 (prev) → touchForehead
      // counter=37037037 (curr) → lookUp. Distinct.
      expect(
        await TotpWords.verifyLivenessAction(
          secret: secret,
          candidate: prev,
          unixTimeSeconds: t,
          senderRole: PairRole.a,
          windowTolerance: 0,
        ),
        isFalse,
      );
    });

    test(
      'at tolerance=0, role-mismatched candidate is rejected '
      '(reflection-attack test — exact-window form)',
      () async {
        // What role b would derive; Alice (role a) must reject this at
        // the exact window. Under tolerance=0 the check is unambiguous.
        // With the default ±1 tolerance, a role-mismatched action can
        // *accidentally* collide with a neighbouring role-correct action
        // (~3/8 per random candidate over the 3-window walk, given the
        // 8-way corpus). The word channel (44 bits) carries the primary
        // reflection defense; the action channel is the belt-and-suspenders
        // overlay. This test pins the exact-window semantics that matter.
        final bAction = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: t,
          senderRole: PairRole.b,
        );
        final aAction = await TotpWords.deriveLivenessAction(
          secret: secret,
          unixTimeSeconds: t,
          senderRole: PairRole.a,
        );
        expect(aAction, isNot(bAction),
            reason: 'fixture sanity: roles diverge at t=$t');

        expect(
          await TotpWords.verifyLivenessAction(
            secret: secret,
            candidate: bAction,
            unixTimeSeconds: t,
            senderRole: PairRole.a,
            windowTolerance: 0,
          ),
          isFalse,
          reason: 'b-role action must not verify as a-role at exact window',
        );
      },
    );

    test('rejects negative windowTolerance', () async {
      expect(
        () => TotpWords.verifyLivenessAction(
          secret: secret,
          candidate: LivenessAction.lookUp,
          unixTimeSeconds: t,
          senderRole: PairRole.a,
          windowTolerance: -1,
        ),
        throwsArgumentError,
      );
    });
  });
}
